version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8  # Choose an appropriate image for your tests
    steps:
      - checkout  # This step checks out your code
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: pytest tests/test_google_search.py

workflows:
  version: 2
  test:
    jobs:
      - test  # Define the job in the workflow
