name: Selenium Test Workflow

on:
  push:
    branches:
      - main  # Change to your target branch name

jobs:
  selenium-tests:
    runs-on: windows-latest  # Can also be 'windows-latest' or 'macos-latest'

    steps:
      - uses: actions/checkout@v2  # Step 1: Check out your repository
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Adjust according to your Python version
      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install your Python dependencies
      - name: Run tests
        run: |
          pytest tests/test_google_search.py  # Adjust your test file path
